baseurl             = "/"
buildDrafts         = false
canonifyUrls        = true
contentDir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Rohan Jain"
title               = "The Perpetual Amature"
pluralizeListTitles = false
theme               = "simple"

[permalinks]
blog  = ":slug/"
fixed = ":slug/"
old = ":slug/"

[params]
author       = "Rohan Jain"
dateForm     = "Jan 2, 2006"
dateFormFull = "Mon Jan 2 2006 15:04:05 MST"
description  = "Rohan's Personal Web Blog."
faviconFile  = "img/favicon.ico"
goatCounter  = "https://t.rohanjain.in"
github       = "//github.com/crodjer"
linkedin     = "//linkedin.com/in/crodjer"
twitter      = "//twitter.com/__crodjer__"
lang         = "en"
blogGroupBy  = "year"
include_rss  = true

[[menu.main]]
name                   = "Home"
weight                 = -9
identifier             = "home"
url                    = "/"
[[menu.main]]
name                   = "About"
weight                 = -8
identifier             = "about"
url                    = "/about/"

[minify]
minifyOutput = true

[minify.tdewolff]
  html = { keepQuotes = false }
  css = { keepCSS2 = true }
  js = { keepVarNames = true }
  json = { keepNumbers = true }
  xml = { keepWhitespace = false }

[markup.highlight]
codeFences = false
